<a href="https://colab.research.google.com/github/anarghya-04/ICSSL_Class1/blob/main/python_intro_CSSL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tools>keyboard shortcuts>change shortcuts

*   ALt+T - text box
*   ALt+C - code box



#Introduction to Python

In [65]:
print ('Welcome to Python') #this is a print statement can use double or single quotes

Welcome to Python


Variables and Expressions

In [66]:
a = 5 #Integer variable
var1 = 10.0 #float variable
str_var = "Alex" #String variable

In [67]:
a

5

In [68]:
var1

10.0

In [69]:
str_var

'Alex'

In [70]:
type(str_var) #Lists the datatype of the variable

str

In [71]:
num1=1
num2=3
num3=num1/num2
num3 #finite precision for floating point numbers (doesn't go upto infinity).

0.3333333333333333

In [72]:
y = var1 + a #Adding int + float
y

15.0

Operators

In [73]:
p = num1+num2 #Addition
q = num1-num2 #Subtraction
r = num1*num2 #Multiplication
s = num1/num2 #Division
t = num1//num2 #Dividend or Integer division
u = num1%num2 #Remainder
print(p,q,r,s,t,u) #print all
print("p =",p) #text and the value
print(f"The value of p is = {p}") #f-string text plus the value in curly brackets. Same as above.

4 -2 3 0.3333333333333333 0 1
p = 4
The value of p is = 4


### Lists

In [74]:
int_list = [1,2,3,4] #A list of Integers
float_list = [1.0,2.5,3.7,5.5] #List of floats
str_list = ["a","b","c","d"] #List of strings
mixed_list = [1,2.4,"a",p] #Mixed list

In [75]:
int_list

[1, 2, 3, 4]

In [76]:
float_list

[1.0, 2.5, 3.7, 5.5]

In [77]:
str_list

['a', 'b', 'c', 'd']

In [78]:
mixed_list

[1, 2.4, 'a', 4]

Aggregate Functions on Lists

In [79]:
sum(int_list) #Sum of all elements

10

In [80]:
len(float_list) #Number of elements in the list

4

In [81]:
sum(mixed_list) # will lead to an error as different datatypes are involved.
sum(str_list) #Also an error

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
int_float_list = int_list+float_list #Combines the two lists
int_float_list

Exercise

In [85]:
scores = [65,78,30,85]
avg_scores = sum(scores)/len(scores) #Calculate the average
max_score = max(scores) #maximum value
min_score = min(scores) #minimun value
print(f"The average score of this class is {avg_scores}, the highest score is {max_score}, and the lowest score is {min(scores)}.")

The average score of this class is 64.5, the highest score is 85, and the lowest score is 30.


Functions and if statements

In [86]:
def has_student_passed(score):
  """
  This is a multiline comment
  This function takes the score and returns pass if
  the score is above 49
  """
  if score>= 40:
    print("The student has passed the course.") # Gets executed if condition evaluates to true
  else:
    print("The student has not passed the course.") # Gets executed if condition evaluates to true
  return 0

For loop

In [87]:
for s in scores:
  print(f"s={s}")
  has_student_passed(s)


s=65
The student has passed the course.
s=78
The student has passed the course.
s=30
The student has not passed the course.
s=85
The student has passed the course.


Homework - Write a function to calculate grades and return the grade.

In [88]:
def get_grade(score):
  """
  This is a multiline comment
  This function takes the score and returns the grade
  """
  if score>= 40 and score <= 50:
    return "E"
  elif score>50 and score<=60:
    return "D"
  elif score>60 and score<=100:
    return "A"
  return "U"

In [82]:
for g in scores:
  print(f"Grade={g},{get_grade(g)}")

Grade=65,A
Grade=78,A
Grade=30,U
Grade=85,A


Help in python

In [83]:
help(sum) #outputs what the function does

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



Dictionaries

In [93]:
score_dict = {"Alex":scores[0],"Nandini":scores[1],"Trisha":scores[2],"John":scores[3]}
score_dict

{'Alex': 65, 'Nandini': 78, 'Trisha': 30, 'John': 85}

## Homework

*   Use the dictionary along with the for loop to print the name and the score of the student.
*   You can also try calculating the grade of each student inside the for block.



In [96]:
score_dict.keys()


dict_keys(['Alex', 'Nandini', 'Trisha', 'John'])

In [97]:
score_dict.values()

dict_values([65, 78, 30, 85])

In [101]:
for key, score in zip(score_dict.keys(), score_dict.values()):
  print(key, scores)

Alex [65, 78, 30, 85]
Nandini [65, 78, 30, 85]
Trisha [65, 78, 30, 85]
John [65, 78, 30, 85]


##NUMPY package

In [102]:
import numpy as np #importing the numpy package

In [105]:
zeros_arr = np.zeros(10) #an array of 10 zeros
zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [106]:
zeros_arr_int_2d = np.zeros(shape = (4,3), dtype = int) #a 2D array of zeros
zeros_arr_int_2d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
ones_arr = np.ones(10) #an array of ones
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [111]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print (f"The first array is {arr1}, the second array is {arr2}")

The first array is [1 2 3 4 5], the second array is [ 6  7  8  9 10]


In [104]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



NUMPY array operations

In [113]:
add_arr = arr1 + arr2 #done element wise
add_arr

array([ 7,  9, 11, 13, 15])

In [114]:
sub_arr = arr1-arr2
sub_arr

array([-5, -5, -5, -5, -5])

In [115]:
mul_arr = arr1*arr2
mul_arr

array([ 6, 14, 24, 36, 50])

In [116]:
div_arr = arr1/arr2
div_arr

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])